# -*- coding: utf-8 -*-
"""Configuración del laboratorio — espejo del Gemelo Digital (Apps Script).
El universo se extrae del Codigo.gs para que ambas herramientas compartan una sola verdad.
PARAMS refleja tu configuración VALIDADA (rejilla 9/9 + backtest: TP=200, trailing 3xATR)."""

VERSION_ALGORITMO = "5.0"   # se sella en cada decisión (principio 2: reproducibilidad)

UNIVERSO = [
    ('AAPL', 'Apple', 'Tecnología'),
    ('MSFT', 'Microsoft', 'Tecnología'),
    ('NVDA', 'NVIDIA', 'Tecnología'),
    ('GOOGL', 'Alphabet', 'Tecnología'),
    ('AMZN', 'Amazon', 'Tecnología'),
    ('META', 'Meta', 'Tecnología'),
    ('AVGO', 'Broadcom', 'Tecnología'),
    ('AMD', 'AMD', 'Tecnología'),
    ('INTC', 'Intel', 'Tecnología'),
    ('QCOM', 'Qualcomm', 'Tecnología'),
    ('ASML.AS', 'ASML', 'Tecnología'),
    ('CRM', 'Salesforce', 'Tecnología'),
    ('ORCL', 'Oracle', 'Tecnología'),
    ('PLTR', 'Palantir', 'Tecnología'),
    ('SAP.DE', 'SAP', 'Tecnología'),
    ('ADBE', 'Adobe', 'Tecnología'),
    ('AMAT', 'Applied Materials', 'Tecnología'),
    ('MU', 'Micron', 'Tecnología'),
    ('ELG.DE', 'Elmos Semiconductor', 'Tecnología'),
    ('TXN', 'Texas Instruments', 'Tecnología'),
    ('NOW', 'ServiceNow', 'Tecnología'),
    ('ARM', 'Arm Holdings', 'Tecnología'),
    ('6758.T', 'Sony', 'Tecnología'),
    ('8035.T', 'Tokyo Electron', 'Tecnología'),
    ('6857.T', 'Advantest', 'Tecnología'),
    ('6861.T', 'Keyence', 'Tecnología'),
    ('7974.T', 'Nintendo', 'Tecnología'),
    ('9984.T', 'SoftBank Group', 'Tecnología'),
    ('RHM.DE', 'Rheinmetall', 'Defensa'),
    ('LDO.MI', 'Leonardo', 'Defensa'),
    ('BA.L', 'BAE Systems', 'Defensa'),
    ('HO.PA', 'Thales', 'Defensa'),
    ('SAAB-B.ST', 'Saab', 'Defensa'),
    ('KTOS', 'Kratos Defense', 'Defensa'),
    ('LMT', 'Lockheed Martin', 'Defensa'),
    ('RTX', 'RTX', 'Defensa'),
    ('NOC', 'Northrop Grumman', 'Defensa'),
    ('GD', 'General Dynamics', 'Defensa'),
    ('HAG.DE', 'Hensoldt', 'Defensa'),
    ('R3NK.DE', 'Renk', 'Defensa'),
    ('LLY', 'Eli Lilly', 'Salud'),
    ('NVO', 'Novo Nordisk', 'Salud'),
    ('JNJ', 'Johnson & Johnson', 'Salud'),
    ('PFE', 'Pfizer', 'Salud'),
    ('MRK', 'Merck', 'Salud'),
    ('NOVN.SW', 'Novartis', 'Salud'),
    ('RO.SW', 'Roche', 'Salud'),
    ('ABBV', 'AbbVie', 'Salud'),
    ('AZN.L', 'AstraZeneca', 'Salud'),
    ('SAN.PA', 'Sanofi', 'Salud'),
    ('MDT', 'Medtronic', 'Salud'),
    ('TMO', 'Thermo Fisher', 'Salud'),
    ('JPM', 'JPMorgan', 'Financiero'),
    ('BAC', 'Bank of America', 'Financiero'),
    ('V', 'Visa', 'Financiero'),
    ('MA', 'Mastercard', 'Financiero'),
    ('ALV.DE', 'Allianz', 'Financiero'),
    ('SAN.MC', 'Santander', 'Financiero'),
    ('BBVA.MC', 'BBVA', 'Financiero'),
    ('ISP.MI', 'Intesa Sanpaolo', 'Financiero'),
    ('GS', 'Goldman Sachs', 'Financiero'),
    ('MS', 'Morgan Stanley', 'Financiero'),
    ('CS.PA', 'AXA', 'Financiero'),
    ('UCG.MI', 'UniCredit', 'Financiero'),
    ('MUV2.DE', 'Munich Re', 'Financiero'),
    ('XOM', 'ExxonMobil', 'Energía'),
    ('CVX', 'Chevron', 'Energía'),
    ('SHEL', 'Shell', 'Energía'),
    ('TTE.PA', 'TotalEnergies', 'Energía'),
    ('ENI.MI', 'Eni', 'Energía'),
    ('NEE', 'NextEra', 'Energía'),
    ('IBE.MC', 'Iberdrola', 'Energía'),
    ('REP.MC', 'Repsol', 'Energía'),
    ('ENEL.MI', 'Enel', 'Energía'),
    ('EOAN.DE', 'E.ON', 'Energía'),
    ('EQNR', 'Equinor', 'Energía'),
    ('COP', 'ConocoPhillips', 'Energía'),
    ('EQIX', 'Equinix', 'Centros de datos'),
    ('DLR', 'Digital Realty', 'Centros de datos'),
    ('VRT', 'Vertiv', 'Centros de datos'),
    ('IRM', 'Iron Mountain', 'Centros de datos'),
    ('CEG', 'Constellation Energy', 'Centros de datos'),
    ('VST', 'Vistra', 'Centros de datos'),
    ('SMCI', 'Super Micro', 'Centros de datos'),
    ('ANET', 'Arista Networks', 'Centros de datos'),
    ('CCJ', 'Cameco', 'Centros de datos'),
    ('KO', 'Coca-Cola', 'Consumo'),
    ('PEP', 'PepsiCo', 'Consumo'),
    ('MCD', 'McDonald’s', 'Consumo'),
    ('NKE', 'Nike', 'Consumo'),
    ('PG', 'Procter & Gamble', 'Consumo'),
    ('MC.PA', 'LVMH', 'Consumo'),
    ('OR.PA', 'L’Oréal', 'Consumo'),
    ('NESN.SW', 'Nestlé', 'Consumo'),
    ('ITX.MC', 'Inditex', 'Consumo'),
    ('SBUX', 'Starbucks', 'Consumo'),
    ('COST', 'Costco', 'Consumo'),
    ('ABI.BR', 'AB InBev', 'Consumo'),
    ('ADS.DE', 'Adidas', 'Consumo'),
    ('DGE.L', 'Diageo', 'Consumo'),
    ('SIE.DE', 'Siemens', 'Industrial'),
    ('AIR.PA', 'Airbus', 'Industrial'),
    ('CAT', 'Caterpillar', 'Industrial'),
    ('GE', 'GE Aerospace', 'Industrial'),
    ('HON', 'Honeywell', 'Industrial'),
    ('ABBN.SW', 'ABB', 'Industrial'),
    ('SU.PA', 'Schneider Electric', 'Industrial'),
    ('DG.PA', 'Vinci', 'Industrial'),
    ('PHIA.AS', 'Philips', 'Industrial'),
    ('TSLA', 'Tesla', 'Automoción'),
    ('VOW3.DE', 'Volkswagen', 'Automoción'),
    ('MBG.DE', 'Mercedes-Benz', 'Automoción'),
    ('BMW.DE', 'BMW', 'Automoción'),
    ('P911.DE', 'Porsche AG', 'Automoción'),
    ('RACE', 'Ferrari', 'Automoción'),
    ('STLAM.MI', 'Stellantis', 'Automoción'),
    ('F', 'Ford', 'Automoción'),
    ('BHP', 'BHP', 'Materiales'),
    ('RIO.L', 'Rio Tinto', 'Materiales'),
    ('BAS.DE', 'BASF', 'Materiales'),
    ('LIN', 'Linde', 'Materiales'),
    ('NEM', 'Newmont', 'Materiales'),
    ('GLEN.L', 'Glencore', 'Materiales'),
    ('FCX', 'Freeport-McMoRan', 'Materiales'),
    ('TEF.MC', 'Telefónica', 'Telecom'),
    ('DTE.DE', 'Deutsche Telekom', 'Telecom'),
    ('VOD.L', 'Vodafone', 'Telecom'),
    ('ORA.PA', 'Orange', 'Telecom'),
    ('SXR8.DE', 'iShares Core S&P 500', 'Fondos'),
    ('EUNL.DE', 'iShares Core MSCI World', 'Fondos'),
    ('IUSQ.DE', 'iShares MSCI World SRI', 'Fondos'),
    ('SXRV.DE', 'iShares Nasdaq 100', 'Fondos'),
    ('EUNN.DE', 'iShares Core MSCI Japan IMI', 'Fondos'),
    ('EXSA.DE', 'iShares STOXX Europe 600', 'Fondos'),
    ('IS3N.DE', 'iShares Core MSCI EM IMI', 'Fondos'),
    ('4GLD.DE', 'Xetra-Gold', 'Fondos'),
    ('BTC-EUR', 'Bitcoin', 'Cripto'),
    ('ETH-EUR', 'Ethereum', 'Cripto'),
    ('SOL-EUR', 'Solana', 'Cripto'),
    ('XRP-EUR', 'XRP', 'Cripto'),
    ('ADA-EUR', 'Cardano', 'Cripto'),
    ('BNB-EUR', 'BNB', 'Cripto'),
    ('DOGE-EUR', 'Dogecoin', 'Cripto'),
]

SECTORES = {t: s for (t, n, s) in UNIVERSO}
NOMBRES  = {t: n for (t, n, s) in UNIVERSO}
TICKERS  = [t for (t, n, s) in UNIVERSO]

PARAMS = {
    # Cartera
    "LIQUIDO_INICIAL": 2000.0, "MAX_POSICIONES": 6, "MAX_POR_SECTOR": 2,
    "CAP_POSICION_PCT": 25.0, "BUFFER_LIQUIDEZ_PCT": 8.0,
    # Señales (score)
    "UMBRAL_COMPRA": 60.0, "UMBRAL_VENTA": 45.0,
    "W_MOMENTUM": 45.0, "W_TENDENCIA": 25.0, "W_POS52W": 15.0, "W_SENTIMIENTO": 10.0,
    "W_FUERZA": 20.0, "W_ROTACION": 15.0, "W_ANALISTAS": 20.0, "W_FUNDAMENTAL": 15.0,
    "W_VOLUMEN": 0.0,   # factor experimental de volumen (0 = desactivado)
    "USAR_ROTACION": True, "ROTACION_TOP": 4,
    # Salidas — CONFIG VALIDADA (rejilla 9/9): dejar correr ganadores, gestiona el trailing
    "STOP_LOSS_PCT": -12.0, "TAKE_PROFIT_PCT": 200.0,
    "USAR_TRAILING": True, "TRAILING_ATR": 3.0, "ATR_PERIODO": 14,
    # Riesgo
    "FILTRO_REGIMEN": True, "MAX_DRAWDOWN_PCT": -20.0,
    "USAR_VOL_TARGET": False, "VOL_OBJETIVO_PCT": 15.0,
    # Fricción (backtest honesto)
    "COMISION": 1.0, "SLIPPAGE_PCT": 0.10, "COOLDOWN_DIAS": 2,
    # Simulación
    "BENCHMARK": "^GSPC", "REBALANCEO_DIAS": 5,
    # Test en vivo (banda vivo-vs-esperado del panel web)
    "TEST_CAGR_ESPERADO": 22.7, "TEST_VOL_ESPERADA": 26.4,
}
